PROJECT_NAME = rng
export PROJECT_NAME

PROJECT_CONFIGURATION_TYPE = release

PROJECT_INCLUDE_PATH := $(CURDIR)/include/c++

PROJECT_CFG_FILE = uig.cfg

PROJECT_CFG_PATH = cfg

PROJECT_LIB_PATH := $(CURDIR)/lib/c++

BOOST_INCLUDE_PATH = /usr/local/include/boost-1_39

export BOOST_INCLUDE_PATH
